import json, random

random.seed(42)

# (word, meaning, [synonyms], [antonyms])
raw = [
("Abate","reduce, lessen",["decrease","subside"],["intensify"]),
("Abhor","hate deeply",["detest","loathe"],["admire"]),
("Abstain","avoid, refrain",["desist","withhold"],["indulge"]),
("Accolade","praise, honour",["award","tribute"],["criticism"]),
("Acumen","sharp intelligence",["insight","wisdom"],["ignorance"]),
("Adversity","hardship",["difficulty","trouble"],["prosperity"]),
("Advocate","support",["recommend","favour"],["oppose"]),
("Alleviate","reduce pain/problem",["ease","relieve"],["worsen"]),
("Amicable","friendly",["cordial","peaceful"],["hostile"]),
("Anarchy","lawlessness",["disorder","chaos"],["order"]),
("Anecdote","short story",["tale","incident"],["long account"]),
("Apathy","lack of interest",["indifference","unconcern"],["enthusiasm"]),
("Arduous","very difficult",["tough","strenuous"],["easy"]),
("Articulate","express clearly",["fluent","clear"],["unclear"]),
("Aspire","aim/desire",["desire","seek"],["abandon"]),
("Audacious","bold/daring",["fearless","daring"],["timid"]),
("Authentic","genuine",["real","original"],["fake"]),
("Avert","prevent",["avoid","stop"],["cause"]),
("Benevolent","kind/generous",["charitable","helpful"],["cruel"]),
("Bolster","support/strengthen",["uphold","reinforce"],["weaken"]),
("Candid","honest/frank",["truthful","open"],["secretive"]),
("Capricious","unpredictable",["fickle","unstable"],["steady"]),
("Coerce","force",["compel","pressure"],["persuade"]),
("Comply","follow rules",["obey","conform"],["violate"]),
("Concur","agree",["consent","approve"],["disagree"]),
("Condone","overlook/forgive",["pardon","excuse"],["condemn"]),
("Conspicuous","easily noticeable",["obvious","visible"],["hidden"]),
("Contradict","oppose/deny",["refute","challenge"],["support"]),
("Conventional","traditional",["usual","standard"],["modern"]),
("Cynical","distrustful",["suspicious","negative"],["optimistic"]),
("Dauntless","fearless",["brave","bold"],["cowardly"]),
("Debilitate","weaken",["impair","exhaust"],["strengthen"]),
("Decipher","decode/understand",["interpret","decode"],["confuse"]),
("Defer","postpone",["delay","adjourn"],["advance"]),
("Demeanor","behaviour",["conduct","attitude"],["misconduct"]),
("Denounce","criticize openly",["condemn","attack"],["praise"]),
("Deplete","reduce/use up",["exhaust","drain"],["replenish"]),
("Derive","obtain from",["get","extract"],["lose"]),
("Deteriorate","become worse",["worsen","decline"],["improve"]),
("Diligent","hardworking",["careful","industrious"],["lazy"]),
("Discreet","careful/cautious",["prudent","tactful"],["careless"]),
("Disdain","contempt",["scorn","disrespect"],["respect"]),
("Disperse","scatter",["spread","distribute"],["gather"]),
("Diverse","varied",["different","varied"],["similar"]),
("Docile","obedient",["submissive","gentle"],["rebellious"]),
("Dormant","inactive",["sleeping","idle"],["active"]),
("Dubious","doubtful",["uncertain","suspicious"],["certain"]),
("Eccentric","unusual/strange",["odd","peculiar"],["normal"]),
("Ecstatic","extremely happy",["delighted","thrilled"],["miserable"]),
("Eloquent","fluent/persuasive",["expressive","articulate"],["inarticulate"]),
("Elusive","hard to find",["evasive","slippery"],["obvious"]),
("Emulate","imitate",["copy","follow"],["ignore"]),
("Enigma","mystery",["puzzle","riddle"],["clarity"]),
("Erratic","irregular",["unstable","unpredictable"],["regular"]),
("Erudite","very knowledgeable",["learned","scholarly"],["ignorant"]),
("Esoteric","understood by few",["obscure","deep"],["common"]),
("Exemplary","ideal/model",["excellent","perfect"],["poor"]),
("Exonerate","free from blame",["acquit","clear"],["convict"]),
("Extravagant","wasteful/costly",["lavish","excessive"],["economical"]),
("Feasible","practical/possible",["workable","possible"],["impossible"]),
("Fidelity","loyalty",["faithfulness","devotion"],["betrayal"]),
("Fluctuate","change often",["vary","swing"],["remain steady"]),
("Frivolous","silly/unimportant",["trivial","foolish"],["serious"]),
("Frugal","economical",["thrifty","saving"],["wasteful"]),
("Futile","useless",["pointless","vain"],["useful"]),
("Garner","collect/gather",["accumulate","obtain"],["scatter"]),
("Gregarious","sociable",["friendly","outgoing"],["reserved"]),
("Grim","serious/harsh",["severe","gloomy"],["cheerful"]),
("Guile","clever deceit",["cunning","trickery"],["honesty"]),
("Hamper","obstruct",["hinder","block"],["help"]),
("Haphazard","random/careless",["unplanned","chaotic"],["organized"]),
("Hostile","unfriendly/aggressive",["enemy-like","opposed"],["friendly"]),
("Hypocrisy","false goodness",["pretence","deception"],["sincerity"]),
("Hypothesis","assumption",["theory","supposition"],["fact"]),
("Illuminate","explain/light up",["clarify","brighten"],["confuse"]),
("Imminent","about to happen",["near","approaching"],["distant"]),
("Impartial","unbiased/fair",["neutral","just"],["biased"]),
("Impediment","obstacle",["hurdle","barrier"],["help"]),
("Implore","beg/request strongly",["plead","beseech"],["command"]),
("Incessant","continuous",["constant","nonstop"],["occasional"]),
("Incisive","sharp/clear",["keen","penetrating"],["vague"]),
("Incompetent","not skilled",["incapable","unfit"],["competent"]),
("Indolent","lazy",["idle","inactive"],["hardworking"]),
("Induce","persuade/cause",["prompt","influence"],["prevent"]),
("Inevitable","certain to happen",["unavoidable","sure"],["avoidable"]),
("Infer","conclude",["deduce","understand"],["misunderstand"]),
("Influx","arrival in large number",["inflow","arrival"],["outflow"]),
("Inhibit","hold back",["restrain","prevent"],["encourage"]),
("Innate","natural/inborn",["inherent","native"],["acquired"]),
("Innovative","creative/new",["original","inventive"],["conventional"]),
("Insolent","rude",["disrespectful","impudent"],["polite"]),
("Intact","complete/undamaged",["whole","safe"],["damaged"]),
("Integrity","honesty",["morality","uprightness"],["dishonesty"]),
("Intricate","complicated",["complex","detailed"],["simple"]),
("Stipulation","condition/rule",["requirement","term"],["disagreement"]),
("Surge","sudden rise",["rise","rush"],["decline"]),
("Incumbent","necessary/duty-bound",["mandatory","obligatory"],["optional"]),
("Precautionary","preventive",["protective","careful"],["careless"]),
("Outcry","public protest/shout",["uproar","protest"],["silence"]),
("Putative","supposed/reputed",["assumed","alleged"],["real"]),
("Sedition","rebellion against authority",["revolt","incitement"],["loyalty"]),
("Wrath","extreme anger",["rage","fury"],["calmness"]),
("Endeavour","try hard",["attempt","strive"],["quit"]),
("Detain","hold back",["stop","restrain"],["release"]),
("Potent","powerful",["strong","effective"],["weak"]),
("Legitimacy","lawfulness",["legality","validity"],["illegality"]),
("Adjudication","formal judgement",["decision","ruling"],["deadlock"]),
("Gratuitous","unnecessary/unjustified",["needless","unwarranted"],["necessary"]),
("Certitude","complete certainty",["confidence","conviction"],["doubt"]),
("Dissent","disagreement",["objection","protest"],["agreement"]),
("Escalation","rapid increase",["rise","hike"],["reduction"]),
("Tussle","struggle/fight",["conflict","scuffle"],["truce"]),
("Propriety","proper behaviour",["decency","decorum"],["indecency"]),
("Defamatory","damaging reputation",["slanderous","insulting"],["complimentary"]),
("Perpetrator","wrongdoer/criminal",["offender","culprit"],["victim"]),
("Abet","assist wrongdoing",["support","encourage"],["prevent"]),
("Disgruntled","dissatisfied/angry",["annoyed","unhappy"],["pleased"]),
("Revamp","improve/renovate",["rebuild","reform"],["damage"]),
("Dispel","remove a doubt/belief",["dismiss","remove"],["create"]),
("Hubris","excessive pride",["arrogance","conceit"],["humility"]),
("Deprivation","lack/denial",["scarcity","deficiency"],["abundance"]),
("Epitomize","be perfect example",["represent","exemplify"],["misrepresent"]),
("Agony","extreme suffering",["pain","misery"],["comfort"]),
("Detriment","harm/damage",["loss","injury"],["benefit"]),
("Repugnant","disgusting/unacceptable",["offensive","hateful"],["pleasant"]),
("Cavalier","careless/disrespectful",["casual","dismissive"],["careful"]),
("Groundswell","strong public rise/support",["surge","wave"],["decline"]),
("Fraudulent","dishonest/fake",["deceitful","false"],["honest"]),
("Overhaul","repair/improve fully",["rebuild","reform"],["neglect"]),
("Unleash","release",["free","let loose"],["restrain"]),
("Surpass","exceed",["outdo","excel"],["lag behind"]),
("Epoch","important period",["era","age"],["moment"]),
("Munificent","very generous",["liberal","bountiful"],["miserly"]),
("Resilience","ability to recover",["toughness","adaptability"],["weakness"]),
("Lure","attract/tempt",["entice","attract"],["repel"]),
("Synergy","combined cooperation",["collaboration","teamwork"],["conflict"]),
("Abjure","reject formally",["renounce","give up"],["accept"]),
("Daunting","difficult/intimidating",["challenging","discouraging"],["easy"]),
("Explicit","clear/direct",["clear","definite"],["vague"]),
("Laudable","praiseworthy",["admirable","commendable"],["shameful"]),
("Paucity","scarcity/lack",["shortage","dearth"],["abundance"]),
("Stringent","strict",["severe","rigid"],["lenient"]),
("Protracted","prolonged",["extended","lengthy"],["brief"]),
("Malign","evil/harmful",["malicious","hostile"],["benevolent"]),
("Vulnerable","exposed to harm",["weak","defenseless"],["protected"]),
("Onerous","burdensome/difficult",["heavy","troublesome"],["easy"]),
("Strife","conflict",["dispute","clash"],["harmony"]),
("Cogent","logical/convincing",["compelling","persuasive"],["weak"]),
("Wary","cautious",["alert","careful"],["careless"]),
("Aloof","distant/unfriendly",["reserved","detached"],["friendly"]),
]

hindi = {
"Abate":"कम होना","Abhor":"घोर घृणा करना","Abstain":"दूर रहना","Accolade":"प्रशंसा/सम्मान",
"Acumen":"कुशाग्रता","Adversity":"विपत्ति","Advocate":"समर्थन करना","Alleviate":"कम करना",
"Amicable":"मैत्रीपूर्ण","Anarchy":"अव्यवस्था","Anecdote":"किस्सा","Apathy":"उदासीनता",
"Arduous":"कठिन","Articulate":"स्पष्ट रूप से व्यक्त करना","Aspire":"आकांक्षा रखना","Audacious":"साहसी",
"Authentic":"प्रामाणिक","Avert":"टालना","Benevolent":"दयालु","Bolster":"मजबूत करना",
"Candid":"स्पष्टवादी","Capricious":"मनमौजी","Coerce":"बाध्य करना","Comply":"अनुपालन करना",
"Concur":"सहमत होना","Condone":"क्षमा करना","Conspicuous":"स्पष्ट रूप से दिखाई देने वाला","Contradict":"विरोध करना",
"Conventional":"पारंपरिक","Cynical":"संदेहवादी","Dauntless":"निडर","Debilitate":"कमजोर करना",
"Decipher":"समझना/कूट खोलना","Defer":"स्थगित करना","Demeanor":"व्यवहार","Denounce":"खुले में निंदा करना",
"Deplete":"समाप्त करना","Derive":"प्राप्त करना","Deteriorate":"बिगड़ना","Diligent":"मेहनती",
"Discreet":"सावधान/विवेकपूर्ण","Disdain":"तिरस्कार","Disperse":"बिखेरना","Diverse":"विविध",
"Docile":"विनयशील","Dormant":"निष्क्रिय","Dubious":"संदेहजनक","Eccentric":"विचित्र",
"Ecstatic":"अत्यंत प्रसन्न","Eloquent":"वाक्पटु","Elusive":"मुश्किल से मिलने वाला","Emulate":"नकल करना",
"Enigma":"रहस्य","Erratic":"अनियमित","Erudite":"विद्वान","Esoteric":"गूढ़",
"Exemplary":"अनुकरणीय","Exonerate":"दोषमुक्त करना","Extravagant":"फिजूलखर्च","Feasible":"व्यवहार्य",
"Fidelity":"वफादारी","Fluctuate":"बदलते रहना","Frivolous":"तुच्छ","Frugal":"मेहनती-बचतकर्ता",
"Futile":"बेकार/निष्फल","Garner":"इकट्ठा करना","Gregarious":"मिलनसार","Grim":"कठोर/गंभीर",
"Guile":"चालाकी/छल","Hamper":"बाधा डालना","Haphazard":"अव्यवस्थित","Hostile":"शत्रुतापूर्ण",
"Hypocrisy":"पाखंड","Hypothesis":"परिकल्पना","Illuminate":"स्पष्ट करना/प्रकाशित करना","Imminent":"निकट भविष्य में होने वाला",
"Impartial":"निष्पक्ष","Impediment":"बाधा","Implore":"विनती करना","Incessant":"निरंतर",
"Incisive":"तीक्ष्ण/स्पष्ट","Incompetent":"अयोग्य","Indolent":"आलसी","Induce":"प्रेरित करना",
"Inevitable":"अवश्यंभावी","Infer":"निष्कर्ष निकालना","Influx":"बड़ी संख्या में आना","Inhibit":"रोकना",
"Innate":"जन्मजात","Innovative":"नवोन्मेषी","Insolent":"अशिष्ट","Intact":"अक्षुण्ण/पूर्ण",
"Integrity":"ईमानदारी","Intricate":"जटिल","Stipulation":"शर्त/नियम","Surge":"उछाल",
"Incumbent":"अनिवार्य/कर्तव्यबद्ध","Precautionary":"सावधानी संबंधी","Outcry":"सार्वजनिक विरोध","Putative":"माना गया",
"Sedition":"राजद्रोह","Wrath":"क्रोध","Endeavour":"प्रयास करना","Detain":"रोकना/हिरासत में लेना",
"Potent":"शक्तिशाली","Legitimacy":"वैधता","Adjudication":"न्यायिक निर्णय","Gratuitous":"अनावश्यक",
"Certitude":"पूर्ण निश्चितता","Dissent":"असहमति","Escalation":"तेज़ी से वृद्धि","Tussle":"संघर्ष",
"Propriety":"औचित्य/शिष्टता","Defamatory":"मानहानिकारक","Perpetrator":"अपराधी","Abet":"दुष्कर्म में सहायता करना",
"Disgruntled":"असंतुष्ट","Revamp":"सुधार करना","Dispel":"दूर करना","Hubris":"अति-अहंकार",
"Deprivation":"वंचना/अभाव","Epitomize":"आदर्श उदाहरण होना","Agony":"असीम पीड़ा","Detriment":"हानि",
"Repugnant":"घृणित","Cavalier":"लापरवाह/अनादरपूर्ण","Groundswell":"जन-समर्थन की लहर","Fraudulent":"धोखाधड़ी से युक्त",
"Overhaul":"पूरी तरह सुधारना","Unleash":"मुक्त करना","Surpass":"पार करना","Epoch":"युग",
"Munificent":"अत्यंत उदार","Resilience":"लचीलापन/उबरने की क्षमता","Lure":"आकर्षित करना","Synergy":"सहक्रिया",
"Abjure":"औपचारिक रूप से त्यागना","Daunting":"कठिन/भयभीत करने वाला","Explicit":"स्पष्ट","Laudable":"प्रशंसनीय",
"Paucity":"कमी/अभाव","Stringent":"सख्त","Protracted":"लंबा खिंचा हुआ","Malign":"दुर्भावनापूर्ण",
"Vulnerable":"असुरक्षित","Onerous":"बोझिल/कठिन","Strife":"संघर्ष/कलह","Cogent":"तर्कसंगत/प्रभावशाली",
"Wary":"सतर्क","Aloof":"उदासीन/दूर रहने वाला",
}

bank_context = {
"Abate":"Inflation is expected to {w} in the coming quarters as RBI tightens monetary policy.",
"Abhor":"Auditors {w} any deviation from compliance norms in loan disbursal.",
"Abstain":"Shareholders chose to {w} from voting on the merger proposal.",
"Accolade":"The bank received an {w} for its digital banking initiative.",
"Acumen":"Strong financial {w} helped the branch manager identify a fraudulent transaction.",
"Adversity":"Despite economic {w}, the bank maintained healthy NPA ratios.",
"Advocate":"The RBI governor continues to {w} for cashless transactions.",
"Alleviate":"The relief package aims to {w} the burden on small borrowers.",
"Amicable":"The two banks reached an {w} settlement over the disputed loan account.",
"Anarchy":"Lack of regulation can lead to financial {w} in unorganized lending markets.",
"Anecdote":"The customer shared an {w} about a delayed fund transfer.",
"Apathy":"Customer {w} towards mobile banking apps is declining as awareness grows.",
"Arduous":"Recovering bad loans is often an {w} process for banks.",
"Articulate":"The relationship manager must {w} the terms of the fixed deposit clearly.",
"Aspire":"Many fintech startups {w} to disrupt traditional banking models.",
"Audacious":"The bank launched an {w} plan to double its rural branch network.",
"Authentic":"Banks verify {w} documents before approving a loan.",
"Avert":"Strong KYC norms help {w} identity theft in banking transactions.",
"Benevolent":"The bank introduced a {w} loan scheme for farmers affected by floods.",
"Bolster":"The capital infusion will {w} the bank's balance sheet.",
"Candid":"The CFO gave a {w} assessment of the bank's rising NPAs.",
"Capricious":"{w} stock market movements affect mutual fund NAVs.",
"Coerce":"No bank official can {w} a customer into buying insurance products.",
"Comply":"All banks must {w} with RBI's new digital lending guidelines.",
"Concur":"The board members {w} with the proposal to raise interest rates.",
"Condone":"The bank will not {w} any lapse in cybersecurity protocols.",
"Conspicuous":"There was a {w} rise in digital transactions post demonetisation.",
"Contradict":"The auditor's report seemed to {w} the branch manager's claims.",
"Conventional":"{w} banking is gradually being replaced by digital-first models.",
"Cynical":"Customers grew {w} about hidden charges on credit cards.",
"Dauntless":"The branch staff remained {w} during the cyberattack attempt.",
"Debilitate":"Mounting NPAs can {w} a bank's lending capacity.",
"Decipher":"Analysts had to {w} the complex loan restructuring terms.",
"Defer":"The borrower requested to {w} the EMI payment for two months.",
"Demeanor":"The teller's calm {w} reassured anxious customers during the system outage.",
"Denounce":"RBI officials {w} the practice of mis-selling insurance with loans.",
"Deplete":"Frequent withdrawals can {w} the reserve fund quickly.",
"Derive":"Banks {w} a major portion of income from interest on loans.",
"Deteriorate":"The asset quality began to {w} during the pandemic.",
"Diligent":"A {w} credit officer cross-checks every loan application thoroughly.",
"Discreet":"Bank staff must remain {w} about customer account details.",
"Disdain":"Customers showed {w} for banks with poor grievance redressal.",
"Disperse":"The crowd outside the branch began to {w} after the system was restored.",
"Diverse":"The bank offers a {w} range of investment products.",
"Docile":"The new recruits were {w} and quick to follow SOPs.",
"Dormant":"A {w} account is reactivated after the customer submits KYC documents.",
"Dubious":"The auditor flagged a {w} transaction in the corporate account.",
"Eccentric":"The investor had an {w} approach to portfolio diversification.",
"Ecstatic":"Customers were {w} after the loan waiver announcement.",
"Eloquent":"The bank's spokesperson gave an {w} explanation of the new policy.",
"Elusive":"Profitability remained {w} for the loss-making branch despite cost cuts.",
"Emulate":"Smaller banks {w} the digital strategies of larger private banks.",
"Enigma":"The sudden default remained an {w} until the forensic audit was completed.",
"Erratic":"{w} repayment behaviour increases a borrower's credit risk.",
"Erudite":"The economist gave an {w} lecture on monetary policy.",
"Esoteric":"Derivative trading involves {w} financial instruments.",
"Exemplary":"The branch received an award for {w} customer service.",
"Exonerate":"The internal probe {w} the manager of any wrongdoing.",
"Extravagant":"{w} spending on credit cards can hurt one's credit score.",
"Feasible":"The restructuring plan was deemed {w} by the loan committee.",
"Fidelity":"Customer {w} to a bank often depends on service quality.",
"Fluctuate":"Interest rates {w} based on RBI's repo rate decisions.",
"Frivolous":"The committee rejected the {w} complaint against the cashier.",
"Frugal":"{w} spending habits help customers maintain a good savings ratio.",
"Futile":"Recovery efforts proved {w} once the borrower declared insolvency.",
"Garner":"The bank aims to {w} more deposits through attractive FD rates.",
"Gregarious":"The {w} branch manager built strong relationships with local businesses.",
"Grim":"The quarterly results painted a {w} picture of rising bad loans.",
"Guile":"The fraudster used {w} to bypass the bank's verification system.",
"Hamper":"Poor internet connectivity can {w} rural digital banking adoption.",
"Haphazard":"{w} record-keeping led to discrepancies in the ledger.",
"Hostile":"The merger faced a {w} reaction from minority shareholders.",
"Hypocrisy":"Critics pointed out the {w} in promoting savings while charging high fees.",
"Hypothesis":"The risk team tested its {w} on default probability using past data.",
"Illuminate":"The annual report helped {w} the bank's exposure to stressed assets.",
"Imminent":"Analysts warned of an {w} rate hike by the central bank.",
"Impartial":"The ombudsman gave an {w} ruling on the customer's complaint.",
"Impediment":"Lack of collateral is a major {w} to getting unsecured loans.",
"Implore":"The borrower had to {w} the bank for a restructuring of dues.",
"Incessant":"{w} phone calls from recovery agents led to a regulatory complaint.",
"Incisive":"The auditor's {w} questions exposed gaps in the loan file.",
"Incompetent":"The branch was flagged for {w} handling of customer grievances.",
"Indolent":"An {w} approach to follow-ups increased the bank's NPA list.",
"Induce":"Attractive interest rates {w} customers to open fixed deposits.",
"Inevitable":"A rate cut seemed {w} given the slowing inflation.",
"Infer":"Analysts {w} a slowdown in credit growth from the latest data.",
"Influx":"The bank saw an {w} of NRI deposits after the new scheme launch.",
"Inhibit":"High collateral requirements {w} small businesses from accessing credit.",
"Innate":"The relationship manager had an {w} ability to read customer needs.",
"Innovative":"The bank rolled out an {w} app feature for instant loans.",
"Insolent":"The customer's {w} behaviour towards staff was reported to the manager.",
"Intact":"The customer's deposit remained {w} despite the merger.",
"Integrity":"Maintaining data {w} is critical for core banking systems.",
"Intricate":"The loan agreement contained {w} clauses on prepayment penalties.",
"Stipulation":"The loan agreement carries a {w} on minimum balance maintenance.",
"Surge":"There was a {w} in digital payments during the festive season.",
"Incumbent":"It is {w} upon every bank to follow RBI's KYC norms.",
"Precautionary":"The bank built a {w} reserve against potential loan defaults.",
"Outcry":"There was a public {w} over the sudden hike in service charges.",
"Putative":"The {w} beneficiary of the fraudulent transfer could not be traced.",
"Sedition":"The case had nothing to do with {w}, but with simple loan fraud.",
"Wrath":"The branch manager faced the customer's {w} over the delayed refund.",
"Endeavour":"The bank will {w} to resolve the complaint within 7 working days.",
"Detain":"Authorities can {w} suspects in large-scale banking fraud cases.",
"Potent":"A {w} combination of digital tools boosted loan disbursal speed.",
"Legitimacy":"KYC verification establishes the {w} of a new account holder.",
"Adjudication":"The ombudsman's {w} favoured the customer in the disputed charge case.",
"Gratuitous":"The bank waived the {w} penalty imposed by mistake.",
"Certitude":"The CFO spoke with {w} about the bank's capital adequacy.",
"Dissent":"Two board members expressed {w} over the proposed merger.",
"Escalation":"The complaint required {w} to the regional grievance officer.",
"Tussle":"A legal {w} arose over the disputed property used as collateral.",
"Propriety":"Bank officials must maintain {w} while handling customer funds.",
"Defamatory":"The bank sued the ex-employee for making {w} remarks online.",
"Perpetrator":"The {w} of the phishing scam was traced through IP logs.",
"Abet":"The employee was suspended for allegedly helping to {w} the fraud.",
"Disgruntled":"A {w} customer filed a complaint about hidden charges.",
"Revamp":"The bank plans to {w} its mobile app for a better user experience.",
"Dispel":"The press release aimed to {w} rumours about the bank's solvency.",
"Hubris":"Analysts blamed the bank's collapse on management {w}.",
"Deprivation":"Financial {w} in rural areas is being addressed through microfinance.",
"Epitomize":"The branch's quick service came to {w} customer-first banking.",
"Agony":"Customers expressed {w} over the prolonged loan approval delay.",
"Detriment":"Ignoring red flags can be to the {w} of the bank's reputation.",
"Repugnant":"Regulators found the predatory lending practice {w}.",
"Cavalier":"A {w} attitude towards documentation led to the loan rejection.",
"Groundswell":"There was a {w} of support for the proposed merger among employees.",
"Fraudulent":"The bank detected a {w} loan application using fake salary slips.",
"Overhaul":"The RBI ordered a complete {w} of the bank's risk management framework.",
"Unleash":"Digital lending platforms {w} faster credit access for MSMEs.",
"Surpass":"The bank's quarterly profit managed to {w} analyst expectations.",
"Epoch":"Digital payments marked a new {w} in Indian banking history.",
"Munificent":"The trust offered a {w} donation to the bank's CSR fund.",
"Resilience":"The banking sector showed strong {w} during the economic slowdown.",
"Lure":"Attractive cashback offers {w} customers to use the new payment app.",
"Synergy":"The merger created {w} between the two banks' branch networks.",
"Abjure":"The whistleblower had to publicly {w} his earlier statement under pressure.",
"Daunting":"Clearing the IBPS exam felt {w} given the vast syllabus.",
"Explicit":"The loan terms must give {w} details on processing fees.",
"Laudable":"The bank's financial inclusion drive received {w} praise from RBI.",
"Paucity":"A {w} of collateral often delays MSME loan approvals.",
"Stringent":"RBI imposed {w} norms on NBFC lending practices.",
"Protracted":"The loan recovery case led to a {w} legal battle.",
"Malign":"Competitors tried to {w} the bank's reputation through false rumours.",
"Vulnerable":"Senior citizens are often {w} to digital banking fraud.",
"Onerous":"Meeting the new compliance deadline proved {w} for smaller banks.",
"Strife":"Labour {w} disrupted operations at the regional processing centre.",
"Cogent":"The analyst presented a {w} argument for cutting interest rates.",
"Wary":"Customers are growing {w} of unsolicited loan approval calls.",
"Aloof":"The new manager seemed {w} during the initial branch visits.",
}

categories = {
}
finance_words = set(["Inflation","Surge","Stipulation","Incumbent","Precautionary","Outcry","Adjudication","Legitimacy",
"Certitude","Dissent","Escalation","Defamatory","Perpetrator","Fraudulent","Overhaul","Resilience","Synergy",
"Stringent","Onerous","Cogent","Influx","Hypothesis","Feasible","Audit"])

def difficulty(word, meaning):
    l = len(word)
    if l <= 6:
        return "Easy"
    elif l <= 9:
        return "Medium"
    else:
        return "Hard"

def category_for(word):
    finance_related = {"Surge","Stipulation","Incumbent","Precautionary","Outcry","Adjudication","Legitimacy",
    "Certitude","Dissent","Escalation","Defamatory","Perpetrator","Fraudulent","Overhaul","Resilience","Synergy",
    "Stringent","Onerous","Cogent","Influx","Feasible","Detriment","Munificent","Frugal","Deplete","Bolster",
    "Garner","Potent","Putative","Gratuitous","Tussle","Disgruntled","Revamp","Groundswell","Paucity"}
    if word in finance_related:
        return "Banking & Finance Vocab"
    return "General Vocabulary"

exams = ["IBPS PO","IBPS Clerk","IBPS SO","SBI PO","SBI Clerk","RBI Grade B","SSC CGL"]

def exam_relevance(idx):
    # deterministic pseudo-random-ish selection so it's stable
    n = 2 + (idx % 3)
    start = idx % len(exams)
    pick = []
    i = start
    while len(pick) < n:
        pick.append(exams[i % len(exams)])
        i += 1
    return pick

data = []
for i, (word, meaning, syn, ant) in enumerate(raw, start=1):
    w_lower = word.lower()
    sentence = bank_context.get(word, "The committee found the manager's response to be {w} during the review.").format(w=w_lower)
    example_general = f"Her {w_lower} attitude surprised everyone at the meeting." if False else None
    item = {
        "id": i,
        "word": word,
        "meaning_en": meaning,
        "meaning_hi": hindi.get(word, ""),
        "synonyms": syn,
        "antonyms": ant,
        "example": sentence,
        "banking_usage": sentence,
        "category": category_for(word),
        "subtype": "Vocabulary",
        "difficulty": difficulty(word, meaning),
        "exam_relevance": exam_relevance(i),
        "pronunciation_hint": word.lower(),
    }
    data.append(item)

with open("/home/claude/vocabapp/vocab.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Generated", len(data), "words")
